### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by qSh4d0w** [The-Nexus-Project/Limitless#1]
I can't even load the modpack it just crashes.
https://pastebin.com/Zr5QESfh

**Comment by Gbergz** [comment]
I've had this problem once & i can help you. Follow these steps:

1. Download forge directly at this link: [https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.14.4-28.1.107/forge-1.14.4-28.1.107-installer.jar](https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.14.4-28.1.107/forge-1.14.4-28.1.107-installer.jar)
2. Open the file.
3. Click the 3 dots on the right side of filepath.
4. Now open Twitch Launcher
5. Right click TNP Limitless in the Mods section and click 'Open Folder'.
6. Go back 2 folders to 'Minecraft'.
7. Open folder 'Install'.
8. Copy the filepath as if it is a normal URL. Example: ['Imgur'](https://i.imgur.com/4bA15JM.png)
9. When you've copied it go back to the installer you downloaded on the first step and follow step 3. 
10. At the "foldername" at the bottom, you're going to paste that link you copied earlier into that space from step 7. Example: [https://i.imgur.com/AXFEa8P.png](https://i.imgur.com/AXFEa8P.png)
11. Now click 'Open'.
12. And finally click 'OK'.
13 Wait for it to complete & profit.
14. Launch the Modpack again.

**Comment by Gbergz** [comment]
Let me know if this works, because it works for me! :)

**Comment by qSh4d0w** [comment]
It works. Thank you! :)

**Comment by cooljackgi** [comment]
works perfect.
thanks

**Comment by kkkkkkhi** [comment]
> I've had this problem once & i can help you. Follow these steps:
> 
> 1. Download forge directly at this link: https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.14.4-28.1.107/forge-1.14.4-28.1.107-installer.jar
> 2. Open the file.
> 3. Click the 3 dots on the right side of filepath.
> 4. Now open Twitch Launcher
> 5. Right click TNP Limitless in the Mods section and click 'Open Folder'.
> 6. Go back 2 folders to 'Minecraft'.
> 7. Open folder 'Install'.
> 8. Copy the filepath as if it is a normal URL. Example: ['Imgur'](https://i.imgur.com/4bA15JM.png)
> 9. When you've copied it go back to the installer you downloaded on the first step and follow step 3.
> 10. At the "foldername" at the bottom, you're going to paste that link you copied earlier into that space from step 7. Example: https://i.imgur.com/AXFEa8P.png
> 11. Now click 'Open'.
> 12. And finally click 'OK'.
>     13 Wait for it to complete & profit.
> 13. Launch the Modpack again.

can you make video please on your explain because i cant do this explain

**Comment by cooljackgi** [comment]
i will do

Am Sa., 11. Jan. 2020 um 14:33 Uhr schrieb kkkkkkhi <
notifications@github.com>:
