### ISSUE TITLE
Recipe Conflict - Yo-yo Cord and Rope Coil

### ISSUE THREAD

**Issue by MarioAndWeegee3** [The-Nexus-Project/Limitless#12]
**Describe the bug**
The Yo-yo Cord and Rope Coil items use the same recipe. For me, the Rope recipe is the one that loads, making crafting the Cord impossible. This keeps you from crafting _any_ of the Yo-yos

**To Reproduce**

1.  Attempt to craft a Cord.

2. Rope Coil is always crafted instead. 

**Expected behavior**
Craft Cord from the Yo-yo mod.

**Screenshots**
![2019-12-22_18 29 02](https://user-images.githubusercontent.com/35458805/71328660-fb93c700-24e8-11ea-9cc9-e41faaf21946.png)

![2019-12-22_18 29 10](https://user-images.githubusercontent.com/35458805/71328663-04849880-24e9-11ea-8675-327cc91fbd6e.png)

**Comment by Gbergz** [comment]
Hey thanks for the report! I'll fix this in the upcoming update. :)
