### ISSUE TITLE
[1.07a] Upgrade Aquatic 1.4.2 causes an Exception that hangs Dedicated Minecraft servers just before start

### ISSUE THREAD

**Issue by TigerWalts** [The-Nexus-Project/Limitless#13]
**Describe the bug**
**Upgrade Aquatic** `1.4.2` causes an Exception that hangs Dedicated Minecraft servers just before start

**To Reproduce**
Steps to reproduce the behavior: (Change steps if required.)
1. Disable the **ShulkerDisplayBox** and **GameMenuModOption** mods (They are not compatible with dedicated servers)
2. Run the modpack using a Forge Server Jar
3. The server will hang just before it loads the world

**Expected behavior**
The world to load/generate and allow connections/commands

**Screenshots**
N/A

**Additional context**
ShulkerDisplayBox and GameMenuModOption are either cosmetic mods or not required on the server, so they can be disabled and players witht he mods active should be able to join. Upgrade Aquatic makes gameplay changes and players joining with the mod disabled on the server may experience unexpected behaviour.

This is known bug with the mod and should be fixed in the next update:
- https://github.com/minecraftabnormals/Upgrade-Aquatic/issues/57

**Crash reports**
N/A

**Comment by Gbergz** [comment]
Are you using the Downloadable server Files or did you put together your own ones?

Download Server Files Here; Should work.
https://www.curseforge.com/minecraft/modpacks/tnp-limitless/files/2843731

**Comment by SmellyModder** [comment]
This has been fixed in the latest version of Upgrade Aquatic: https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic/files/2848789

**Comment by Gbergz** [comment]
Looks like this will be fixed in the upcoming scheduled update on the 26th. Closing. Thanks !
