### ISSUE TITLE
Error when opening Crafting Station

### ISSUE THREAD

**Issue by Horang1173** [The-Nexus-Project/Limitless#15]
"Bad recipe crafttweaker:shaped_emeraldpaxel found, see log for details" error
Occurs when opening a Crafting Station.
Rotating a recipe also causes the items in the 1st, 2nd, and 4th, slots (in a 9 slot grid) to be deleted.
Recipe rotation issue only occurs on a server.
Issue can be manipulated to duplicate items (item is "gone" in crafting grid, but product remains. Can pull stack of product without item being used allowing for unlimited crafts of the item)
*edit* server reset seems to have fixed this issue!

**Comment by Gbergz** [comment]
Server restart appears to have fixed the issue, good!
Re-open if anything else happens.
