### ISSUE TITLE
Extra Golems main item "Golem Spell" cannot be created due to recipe overwrite

### ISSUE THREAD

**Issue by Horang1173** [The-Nexus-Project/Limitless#17]
**Describe the bug**
Also remember to report it to the Mod Author if you can indentify which mod it is!

Recipe for "Golem Spell" overwritten by CCtweaks "floppydisc"

**To Reproduce**
Steps to reproduce the behavior: (Change steps if required.)
1. Go to make a Golem Spell
2. Mats will automatically look to create a floppy disc

**Expected behavior**
Golem Spell created
**Screenshots**

**Additional context**

**Crash reports**
Put any crash reports here.

**Comment by Gbergz** [comment]
Thanks for the report! I'll go ahead and fix this for an upcoming "a" update. (1.08a). 👍
