### ISSUE TITLE
Fast creation of heavenly seeds (seems to be a bug/glitch) *Edit no essence

### ISSUE THREAD

**Issue by Horang1173** [The-Nexus-Project/Limitless#18]
**Describe the bug**
Also remember to report it to the Mod Author if you can identify which mod it is!
When using a hoe on a fully grown heavenly seed base (growing on tilled soil) it will till the plant without resetting the growth time. This means you can hold right click and gain unlimited harvests. This plant also does not drop essence when harvested.
**To Reproduce**
Steps to reproduce the behavior: (Change steps if required.)
1. Plant and grow a base heavenly seed on tilled soil
2. Equip a hoe
3. Right click the seed to harvest with the hoe
4. Hold right click to continue harvesting large amounts of seed

**Expected behavior**
Expected the seed to revert back to growth stage 1
**Screenshots**

**Additional context**

**Crash reports**
Put any crash reports here.

**Comment by Gbergz** [comment]
Mod removed in v1.10
