### ISSUE TITLE
Crash when playing LAN

### ISSUE THREAD

**Issue by Campermangreg** [The-Nexus-Project/Limitless#2]
Hello there.
I've just started playing this modpack over LAN and for some reason only one of us is getting this crash report:

[crash-2019-10-09_21.35.40-client.txt](https://github.com/The-Nexus-Project/Limitless/files/3709329/crash-2019-10-09_21.35.40-client.txt)

**Comment by Gbergz** [comment]
Heya! 
If both of you go into the "mods" folder & remove the mod "damage_indicator-0.0.7.jar" and then try without it. See if it works. I'll report this issue to the Damage Indicator mod developer.

EDIT: If that doesn't work try downloading the server files & setting the server up that way, i have tested and i've not received that specific crash there.

**Comment by Campermangreg** [comment]
Removing damaged indications seemed to do the job!

Thanks for that.
