### ISSUE TITLE
Can't break plants, sometimes

### ISSUE THREAD

**Issue by gh0st31337** [The-Nexus-Project/Limitless#20]
**Describe the bug**
I am having an issue where I am not able to break plants.  It will work just fine, then start not allowing me to break them.  They break and immediately replant.  

**To Reproduce**
Steps to reproduce the behavior: (Change steps if required.)
1. Attempt to break plant
2. Watch plant break and then immediately replant
3. Rinse and repeat

**Expected behavior**
The plants should break as normal and go into the inventory.

**Screenshots**
![2019-12-30_21 49 23](https://user-images.githubusercontent.com/10960157/71608360-adb53980-2b4e-11ea-945c-9866d6d87192.png)
![2019-12-30_21 49 31](https://user-images.githubusercontent.com/10960157/71608361-adb53980-2b4e-11ea-9cc1-d8b3d7366985.png)
![2019-12-30_21 49 38](https://user-images.githubusercontent.com/10960157/71608362-ae4dd000-2b4e-11ea-9479-6da9fc9c86ca.png)
![2019-12-30_21 49 42](https://user-images.githubusercontent.com/10960157/71608363-ae4dd000-2b4e-11ea-9955-52bf90369be7.png)
![2019-12-30_21 52 07](https://user-images.githubusercontent.com/10960157/71608364-ae4dd000-2b4e-11ea-86c4-871f2082b325.png)

**Additional context**
Hopefully you can see somewhat in the screenshots what is happening.  I also am showing the helmet that has magnet on it.  If I have magnet on my gear I can stand away from them when I break them and they will float towards me and then sometimes replant right in front of me.  I am not seeing any errors in the server logs or the client logs.  However, the client log is filling with the message "Fired".

**Crash reports**
None

**Comment by Gbergz** [comment]
Hello, i have completely no idea what could be causing this.
Without nothing showing in logs or similar it's gonna be hard to know. Sorry!


Though the "Event Fired" in the logs and server console is from the mod Ender Enhancement and is fixed in the latest version of the pack along with other stuff. Version: [1.08a](https://www.curseforge.com/minecraft/modpacks/tnp-limitless/files/2852408).

Read the changelog for it here; [https://github.com/The-Nexus-Project/Limitless/blob/master/Changelog.md](https://github.com/The-Nexus-Project/Limitless/blob/master/Changelog.md)

EDIT: My guess would be it has something to do with the Magnet Enchantment.

**Comment by gh0st31337** [comment]
It's there a mod that automatically plants things that fall on the ground?
I noticed today that when I was cutting down trees that some of the
saplings would plant themselves when they hit the ground.

**Comment by Gbergz** [comment]
Yes there's a mod that re-plants them or rather integrated into a bigger mod. I have no idea what it's called currently though.. I can understand that its annoying.

**Comment by gh0st31337** [comment]
I found something in the config that is probably doing it. It's in this
file Limitless/config/vanillatweaks/world.toml

I will try to disable this later and see if that fixes the issue.

**Comment by Gbergz** [comment]
Yes that is probably it!
For 1.09 i'll disable that.
Thanks for the report.

**Comment by gh0st31337** [comment]
> Though the "Event Fired" in the logs and server console is from the mod Ender Enhancement and is fixed in the latest version of the pack along with other stuff. Version: [1.08a](https://www.curseforge.com/minecraft/modpacks/tnp-limitless/files/2852408).

These errors are still spamming the client logs on 1.0.8a.

**Comment by Gbergz** [comment]
Noticed this aswell. Though they are coming from another mod this time.
I'll try to fix this for v1.09!
