### ISSUE TITLE
Can't join the server, am a total noob... please help.

### ISSUE THREAD

**Issue by FarizTGK** [The-Nexus-Project/Limitless#21]
[m[32m[13:11:57] [Server thread/INFO] [minecraft/DedicatedServer]: FarizTheMVP joined the game
[m[1;31m[13:11:58] [Netty Server IO #1/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIdArgument@1d1290c8 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
[m[1;31m[13:11:58] [Netty Server IO #1/ERROR] [minecraft/ArgumentTypes]: Could not serialize com.blamejared.crafttweaker.impl.commands.CTCommands$$Lambda$12453/619139720@165e1179 (class com.blamejared.crafttweaker.impl.commands.CTCommands$$Lambda$12453/619139720) - will not be sent to client!
[m[1;31m[13:11:58] [Netty Server IO #1/ERROR] [minecraft/ArgumentTypes]: Could not serialize com.blamejared.crafttweaker.impl.commands.CTCommands$$Lambda$12469/1402333484@60608ed6 (class com.blamejared.crafttweaker.impl.commands.CTCommands$$Lambda$12469/1402333484) - will not be sent to client!
[m[1;31m[13:11:58] [Netty Server IO #1/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@1998e892 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
[m[ApotheosisCore]: Patching CombatRules#getDamageAfterMagicAbsorb
[32m[13:12:27] [Server thread/INFO] [minecraft/ServerPlayNetHandler]: FarizTheMVP lost connection: Disconnected
[m[32m[13:12:27] [Server thread/INFO] [minecraft/DedicatedServer]: FarizTheMVP left the game
[m[32m[13:20:00] [Server thread/INFO] [tombstone/]: All players have been successfully backed up

**Comment by Gbergz** [comment]
You gonna have to provide more information. And also use Paste sites like ”Paste.ee”, ”pastebin” & ”Gist GitHub”.
Logs, debug logs, crash reports.

Feel free to te-open this if the issue still happens.
