### ISSUE TITLE
Repeat server Crash unable to connect at times

### ISSUE THREAD

**Issue by Wolfgaing6** [The-Nexus-Project/Limitless#23]
**Describe the bug**
when a player joins the server it crashes out on server console it spams the following message each time """

**To Reproduce**
Steps to reproduce the behavior: (Change steps if required.)
1. any time one of the 3 of us connect to the server
2. just join server

**Additional context**
also noticed server crashing with some enchantments such as Excavate X or mining fervor causing mining and crashing issues crashing stopped once enchantments removed

**Comment by Gbergz** [comment]
Hello, when posting logs, debug logs & crash reports. Please use Paste sites like: Pastebin. Paste.ee, GistGithub, Hastebin.

**Comment by Wolfgaing6** [comment]
sorry I was just following the list was not familiar with pastebin or any of the programs i Hope this is correct..

[tnp_limitless_player_crash.txt](https://github.com/The-Nexus-Project/Limitless/files/4016082/tnp_limitless_player_crash.txt)

**Comment by Wolfgaing6** [comment]
[updated_crash_report.txt](https://github.com/The-Nexus-Project/Limitless/files/4026850/updated_crash_report.txt)

but anytime we connect it crashes out could it be caused by not having same start up parameters?

no items in inventory other than forbidin and acanus pickaxe and axe as well as angel ring

**Comment by Wolfgaing6** [comment]
up Dated to current version issue seems cleared currently thank you for the time
