### ISSUE TITLE
Fluidtanks Recipes Not Working

### ISSUE THREAD

**Issue by gh0st31337** [The-Nexus-Project/Limitless#24]
**Describe the bug**
The recipes for the tank above the wooden tank do not work in game.

**To Reproduce**
1. Make wooden tanks from Fluidtanks
2. Try to make any tier above wooden

**Expected behavior**
The ability to craft higher tier tanks

**Screenshots**
n/a

**Additional context**
The recipes seem to be broken, none of the tank above the wooden tanks actually have any other material in the recipe other than the wooden tanks.

**Crash reports**
n/a

**Comment by Gbergz** [comment]
Just tried this on a Server & Singleplayer. Everything appears to be in order(working).
Saw you reported CraftTweaker Errors earlier aswell. To me they seem connected. If errors spew out maybe some recipes stop working. Need to follow up on this one.

Images:
Wood Tank: [https://i.imgur.com/oIGp2qA.png](https://i.imgur.com/oIGp2qA.png)
Stone Tank: [https://i.imgur.com/oIGp2qA.png](https://i.imgur.com/oIGp2qA.png)
Iron Tank: [https://i.imgur.com/oIGp2qA.png](https://i.imgur.com/oIGp2qA.png)

**Comment by Gbergz** [comment]
Just tried this on a Server & Singleplayer. Everything appears to be in order(working).
Saw you reported CraftTweaker Errors earlier aswell. To me they seem connected. If errors spew out maybe some recipes stop working. Need to follow up on this one.

Images:
Wood Tank: [https://i.imgur.com/oIGp2qA.png](https://i.imgur.com/oIGp2qA.png)
Stone Tank: [https://i.imgur.com/oIGp2qA.png](https://i.imgur.com/JTzJEYu.png)
Iron Tank: [https://i.imgur.com/oIGp2qA.png](https://i.imgur.com/gozA2rO.png)

**Comment by gh0st31337** [comment]
For some reason they are working now.  I was able to craft the higher tier tanks.  I wonder if its related to the crafttweaker bug, which also showed up during this playthrough and then went away mysteriously with no restarts.

**Comment by Gbergz** [comment]
Closing this, reopen if further issues appear.
