### ISSUE TITLE
Getting recipe errors when clicking on crafting table

### ISSUE THREAD

**Issue by gh0st31337** [The-Nexus-Project/Limitless#25]
**Describe the bug**
When clicking on the crafting table a bunch of errors show up in the chat window and on the server logs, since the 1.0.8a update.

**To Reproduce**
1. Update to 1.0.8a
2. Click on any crafting table

**Expected behavior**
No errors for recipes.

**Screenshots**
![2020-01-02_15 11 33](https://user-images.githubusercontent.com/10960157/71690304-437cde80-2d72-11ea-9886-95c689cd2947.png)

**Additional context**
Server errors:
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: Bad recipe found: crafttweaker:shaped_amethysthelmet
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: null
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: Bad recipe found: crafttweaker:shaped_amethystaxe
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: null
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: Bad recipe found: crafttweaker:shaped_tinhelmet
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: null
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: Bad recipe found: crafttweaker:shaped_shellshovel
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: null
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: Bad recipe found: crafttweaker:shaped_amethystknife
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: null
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: Bad recipe found: crafttweaker:shaped_amethystsword1
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: null
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: Bad recipe found: crafttweaker:shaped_amethystsword2
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: null
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: Bad recipe found: crafttweaker:shaped_copperknife
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: null
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: Bad recipe found: crafttweaker:shaped_leadsword1
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: null
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: Bad recipe found: crafttweaker:shaped_leadsword2
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: null
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: Bad recipe found: crafttweaker:shaped_tinhelmet2
[m[1;31m[15:06:19] [Server thread/ERROR] [co.tf.cr.CraftingStation/]: null

**Crash reports**
n/a

**Comment by Gbergz** [comment]
Try restarting the game. Doesn't happen everytime. Seems to be a bug of some sort.

**Comment by gh0st31337** [comment]
If it helps, I think it might have to do with the mod that adds those
shortcut buttons that allow you to easily spread out items in the creating
table.

**Comment by Gbergz** [comment]
If you can next time this happens. Provide me with the whole logs, crafttweaker logs

**Comment by gh0st31337** [comment]
Here are the logs because it happened again.

[crafttweaker.log](https://github.com/The-Nexus-Project/Limitless/files/4020779/crafttweaker.log)
[latest copy.log](https://github.com/The-Nexus-Project/Limitless/files/4020782/latest.copy.log)

**Comment by craft90** [comment]
I ran into this myself. It seems to happen when using the Crafting Station that's connected to a chest. A regular vanilla crafting bench doesn't have the issue. Nor the SilentGem Crafting Station (though that one ran into some issue where it refuse to reopen, forcing me to break it. I have no idea why that happened though). Maybe it makes a bad call to CraftTweaker? For me it seemed to corrupt the entire recipe database aswell as I couldn't craft anything. (But that could also be due to the block it occupied being a bad error block. I didn't test it further and instead restarted. After a restart it worked as it should.)

**Comment by gh0st31337** [comment]
I noticed the silent gems creating station was deleting my items when using
mouse tweaks shortcuts. So I stopped using it.

**Comment by NorgerLegacy** [comment]
every crafting table i seem to lose items they disappear normal crafting table or crafting station.  plus get the crafting station error with it attached to a chest. maybe switch to vanilla crafting station not fast workbench, i dont see the benefit for it anyways

**Comment by Gbergz** [comment]
@NorgerLegacy What version of the pack were you experiencing this in?

**Comment by gh0st31337** [comment]
This was in 1.0.7 and 1.0.8.  I haven't had any issues since then and now
I'm running 1.0.9, but like I said, I stopped using that silent gems
crafting station.

**Comment by Gbergz** [comment]
Update to Version 1.10, i might've been fixed in that version.
