### ISSUE TITLE
Recipe conflicts

### ISSUE THREAD

**Issue by craft90** [The-Nexus-Project/Limitless#26]
I have noticed a few conflicts with cooking recipes.

First of all Mystical World cooked vegetables. When cooked in a regular furnace or the smoker instead of returning the cooked version (Cooked Carrot, Cooked Beetroot) it returns Animal Feed from Essetials. Cooking them on the campfire (vanilla MC) does return the cooked vegetable item. This conflict breaks recipes which request the cooked vegetable unless you use the campfire.

Secondly the Edelwood from Forbidden & Arcanus. When checking the recipes in JEI the Edelwood has two returns, charcoal and dark matter. Cooking it in a furnace returns charcoal rather than Dark Matter. This seems to be due to Edelwood registering as a "very poor barter item". Meanwhile the crafting recipe for Dark Matter only reference the regular Edelwood cooking recipe.

In addition I also noticed that the the tea crop from Tea and Biscuits does not drop tea leaves for some reason. I'm not sure if it's due to a conflict or a bug in the original mod however. Another farming issue I found was the grapes crop from Simple Farming doesn't seem to drop anything but seeds when broken. Even when it's supposed to be matured.

**Comment by Gbergz** [comment]
Heya! Thanks for the report. 
I've gone ahead and fixed the Cooked Vegetable recipe conflict & the Edelwood recipe conflict.

The Tea Biscuits & Simple farming seems like a hard issue to trace down. If not fixed for 1.09 i'll try for another update!

**Comment by craft90** [comment]
Thank you! The modpack has renewed my desire to play modded MC again so I'm quite keen on the pack working as it should. I'd know the hassle of making 1.14 modpacks myself. Hence why I didn't.
