### ISSUE TITLE
Crafting tables not working after some time and giving weird return

### ISSUE THREAD

**Issue by Kazemaho** [The-Nexus-Project/Limitless#30]
After a time, the crafting in tables doesn't work aymore.

The result of the recipe never show and the items you put in the table just comes back in your inventory or simply disapeared (seems random) when you try to get them back or close the table.

 I'm on my way to craft an assembly halo and will let you know if the issue appears again with this one.

**Comment by Gbergz** [comment]
Still happening?

**Comment by Gbergz** [comment]
This has been fixed for awhile. Closing,
