### ISSUE TITLE
Pillager Outpost Freezes/Crashes Server

### ISSUE THREAD

**Issue by RedBlockCreator** [The-Nexus-Project/Limitless#31]
**Describe the bug**
Server freezes and eventually crashes due to taking too long to tick (60 seconds) when at a pillager outpost. Kind of game breaking.

**To Reproduce**
Go to a pillager outpost on a server. After being there long enough it seems to freeze completely.

**Expected behavior**
It should not crash the server

**Crash reports**
Don't have any errors, server just freezes and then crashes from taking too long to tick

**Comment by Gbergz** [comment]
Is this still happening? Starting to believe it's actually this [Illager+](https://www.curseforge.com/minecraft/mc-mods/illagers) mod that's causing the freezes. Had a total of 5 "freezes" today and all are pointing towards this mod. If you're willing to test you can remove the mod and see if it still happens.

**Comment by Gbergz** [comment]
Closing this, re-open if needed.
