### ISSUE TITLE
Path error on startup.

### ISSUE THREAD

**Issue by GNiessen** [The-Nexus-Project/Limitless#32]
This may be more of a curses issue, but I get an error on start up:
Failed to find Minecraft resource version 1.14.4-20190829.143755 at C:\Users\Gordon 

The problem is I have a space in my windows user name: "Gordon Niessen"  and it is breaking the command on the space.  How can I fix this?

**Comment by Gbergz** [comment]
Follow this guide see if works!
https://github.com/The-Nexus-Project/Limitless/issues/1

**Comment by greggregface** [comment]
I'm having difficulties with the Main window even loading the modpack. I'm on macOS just fyi, but I downloaded the forge file and redownloaded the pack multiple times to no avail. Help?

**Comment by Gbergz** [comment]
macOS users has had trouble loading the pack sadly. One user installed Windows onto the macOS machine and then it worked flawlessly.

**Comment by Gbergz** [comment]
Closing this. Re-open if further help is needed.

**Comment by Nonsanity** [comment]
How I got this pack (or any 1.14 pack, for that matter) working on Mac:

Install Vanilla 1.14 Minecraft. In the launcher's settings, switch to the alpha launcher (requires re-launch of the program). Download the currently correct version of the Forge Installer (28.1.107 as I write this) that the pack uses and run it to install into Minecraft's directory. Then open up your (non-working) Twitch install folder for the TNP pack and move the config, defaultconfigs, mods, openloader, & script folders to the Minecraft install directory. Now launch Minecraft and choose Forge from the pop-up menu next to the Play button. Push Play button.

It's not a simple procedure but it you are moderately familiar with how modded Minecraft directories are set up, you shouldn't have much trouble. If you do mess up, it's not too hard to start over from scratch.

Hope that helps.
