### ISSUE TITLE
Silent Gear bow - Server crash if pressing Bow Upgrade button

### ISSUE THREAD

**Issue by dotParx** [The-Nexus-Project/Limitless#33]
**Describe the bug**
Holding a bow crafted from Silent's Gear and pressing "B" (Default) to upgrade your bow will cause the server to instantly shut down.

**To Reproduce**
1. Build Silent's Gear Bow
2. Hold in hand
4. Press B (not displayed on bow)

**Expected behavior**
Nothing would happen, or other B mappings would take place.

--
Not my server, accessing logs would require a delay.

**Comment by Gbergz** [comment]
I would need the Crash report to really know anything. 
See if you can acquire it somehow!

Edit: I'll see if i can reproduce it myself.

**Comment by dotParx** [comment]
Crash log
[crash-2020-01-12_15.01.26-server.txt](https://github.com/The-Nexus-Project/Limitless/files/4050753/crash-2020-01-12_15.01.26-server.txt)

Latest Log
[latest.log](https://github.com/The-Nexus-Project/Limitless/files/4050754/latest.log)

**Comment by Gbergz** [comment]
This kind of issue is known. Currently have no idea what causes it. Will try to fix it in a future update.
Sorry for this. I know it's annoying.

Edit: It has nothing to do with Silent Gears bows.
