### ISSUE TITLE
Server crash acquiring water in edelwood bucket

### ISSUE THREAD

**Issue by dotParx** [The-Nexus-Project/Limitless#34]
**Describe the bug**
Attempting to retrieve water in an Edelwood bucket will result in an immediate server crash.

**To Reproduce**
Steps to reproduce the behavior: (Change these steps if required.)
1. Craft Edelwood Bucket
2. Pick up water
3. Turn server back on

**Expected behavior**
Acquire Edelwood Water Bucket

**Crash reports**
Not my server, but can spin one up and reproduce for logs if needed.

**Comment by Gbergz** [comment]
Same as your last report, need the logs & crash report.
Edit: I'll see if i can reproduce it myself.
Thanks for the report though!

**Comment by Gbergz** [comment]
Might've been fixed in the mod. Re-open if you're still experiencing this.
