### ISSUE TITLE
start up crash

### ISSUE THREAD

**Issue by MonsterEats** [The-Nexus-Project/Limitless#35]
i know this has been said before however i have a different issue with it. so basically it wont start up, i click the play button on twitch its says applying patch 2 of 4 and then loads. then i press the play button on the native launcher it starts up a fml early loading process and crashes. 

i have tried #1 issue and it hasnt fixed it.

[DED3DTQu.txt](https://github.com/The-Nexus-Project/Limitless/files/4056217/DED3DTQu.txt)
 here is the log i get 

any help would be great thanks!

**Comment by Gbergz** [comment]
Gonna need a debug log or the complete log. Gonna close this. 

REOPEN if you can provide complete logs / debug log.
