### ISSUE TITLE
Mod FluidTank and JEI recipe

### ISSUE THREAD

**Issue by NorgerLegacy** [The-Nexus-Project/Limitless#36]
Limitless 1.14.4 -v1.10a
if you craft 4 wood tanks (1 in each corner) and put in crafting station or crafting table (crafting grid - refined storage does not work) it shows tin tank not stone (if you try to remove nothing happens it will not make it. JEI shows stone tank as just 4 wood tanks in corner. However if you put 1 in each corner and put 1 stone in the remaining spots on the grid it will make 1 stone tank. 

have restarted minecraft logged back into server same result. tried java 8 latest 64 and 32.
Pack is updated. not showing any crashes or error in the debug screen

**side note fluid storage tank cyclic - havent looked to see but does not retain liquid after tank is broken**

**Java Info:**
 - Java Version: 8
 - 64bit/32bit: tried both

**My OS (Win10)**
- 

**Additional context**
playing on server
![fluidtanks crafting grid](https://user-images.githubusercontent.com/56412152/72588273-bf743c00-38c5-11ea-886f-2401c5f75b01.png)
![fluidtanks jei stonetankrecipe](https://user-images.githubusercontent.com/56412152/72588276-c307c300-38c5-11ea-96a9-fbbc3947bc12.png)
![fluidtanks recipe broke shows tin but wont let you take it](https://user-images.githubusercontent.com/56412152/72588279-c602b380-38c5-11ea-9a90-fe509d39a4e0.png)
![fluidtanks stone tank recipe working](https://user-images.githubusercontent.com/56412152/72588285-c8fda400-38c5-11ea-8bd6-cba638b45332.png)

**Comment by NorgerLegacy** [comment]
oh all next level recipe for tanks show just 1 tank of previous level in each corner, havent tried each level to verify if those have same issue.

**Comment by Gbergz** [comment]
Seems weird that you do not need Tin in order to craft a Tin Tank. I'll look into a fix.

**Comment by Gbergz** [comment]
Appears I do not have the same recipes as you do. All recipes are working as expected. Really strange to be honest. Hmm...
____
**Wood Tank Recipe**: 
![Woodtank](https://user-images.githubusercontent.com/26634554/72609221-b1093d00-3924-11ea-9c04-a42296127204.png)

**Stone Tank Recipe**: 
![Stonetank](https://user-images.githubusercontent.com/26634554/72609231-b5cdf100-3924-11ea-9120-5146d1af0a21.png)

**Tin Recipe**: 
![Tintank](https://user-images.githubusercontent.com/26634554/72609244-bbc3d200-3924-11ea-8475-99d5a0adc185.png)
