### ISSUE TITLE
Server won’t load world file

### ISSUE THREAD

**Issue by camcamhow** [The-Nexus-Project/Limitless#37]
i went to port over my world from mod pack version 1.09 to 1.10a and the server won’t load the world file

**Comment by Gbergz** [comment]
Did you do ``fml confirm`` / ``/fml confirm`` in the Console ?

**Comment by camcamhow** [comment]
I feel so stupid

**Comment by camcamhow** [comment]
Thank you

**Comment by Gbergz** [comment]
Haha it happens! Glad you got it running again. :)
