### ISSUE TITLE
Block breaking glitch/bypass

### ISSUE THREAD

**Issue by camcamhow** [The-Nexus-Project/Limitless#38]
**Describe what happened:**
I broke a vanilla block with a Gobber hammer

**To Reproduce**
Steps to reproduce (double-check if you can do it yourself):
1. Place Security Craft Reinforced Blocks in a row and place a normal vanilla block I found out with Glowstone
2. Take a Gobber Nether hammer
3. and break the vanilla block
4. you can use a rubber hammer to bypass the security craft blocks

**Expected behaviour**
if possible stop Gobber hammers from being able to bypass security craft block

**My OS Win10

**Comment by Gbergz** [comment]
If this is still happening report it on the mods issue tracker.
