### ISSUE TITLE
Opens 1.6.9 Minecraft launcher

### ISSUE THREAD

**Issue by raymondlucifer66** [The-Nexus-Project/Limitless#39]
idk with this one, I tried #1 and I didn't work everything appears fine until the ancient 1.6.9 launcher appears, I can't provide a crash log since it technically didn't crash.

I'm just at a loss with this one.

**Comment by raymondlucifer66** [comment]
I'm just at a loss with this.

**Comment by Gbergz** [comment]
I don't really know what this issue is about, seems like you provided no information on how I can help.
Mind trying out this Launcher? See if it works for you.
[https://gdevs.io/](https://gdevs.io/)

**Comment by raymondlucifer66** [comment]
yea well idrk how to explain it I gave the pack 9gigs I gave the Minecraft launcher 9gigs I changed the launcher to the JAR one it's just confusing when it literally launches the 1.6.9 Minecraft launcher but ill try that out and see how it goes.

**Comment by raymondlucifer66** [comment]
Yea that launcher did work, I still don't know why the fuck it opened 1.6.9 but whatever idgaf anymore
