### ISSUE TITLE
New Golem mod

### ISSUE THREAD

**Issue by Campermangreg** [The-Nexus-Project/Limitless#4]
Love the new Golem mod think its a great addition to the game,

I've moved two new villagers over to my house and levelled them up by trading with them.

when doing this i found the the spawning of the Golems went nuts!!! (See picture attached)
![2019-10-20_10 31 24](https://user-images.githubusercontent.com/6351408/67157515-32046880-f325-11e9-9cf9-995385fc3d13.png)

I looked in the config and noticed the spawn rate was set to a 90% chance so you might want to set this to a much lower number in your next update.

**Comment by Gbergz** [comment]
Hey! Thanks for reporting this.
I've lowered the value from 90 > 16 for the next update.

Let me know if i need to change it even further when next update is released.
