### ISSUE TITLE
RFTools Builder is not voiding cobblestone, sand, dirt, etc.

### ISSUE THREAD

**Issue by lasiecz** [The-Nexus-Project/Limitless#40]
Hi there,

I am having problem with RFTools Builder - in my singleplayer world I set Quarry with Shape Card (Clearing Quarry) and I tick the choice to void items like cobble, snad, dirt but it is not working - all the cobble, dirt, etc. is still going into my inventory. So I tried the same setup in creative world and here it is working so I am very confused. 

I went through the config and didn't find a single thing that would disable using void in SP world.

Any tips?

Thank you very much,

Lenka

![2020-01-18_20 12 40](https://user-images.githubusercontent.com/12786747/72677511-71b22c00-3a9d-11ea-9566-e1ecf294ad8f.png)

**Comment by Gbergz** [comment]
Sounds strange! Could be an "error" in the mod, who knows.

Mind reporting it to the Dev? If he just throws you back here then i'll do my best to solve it. But I can't guarantee that it'll be fixed.

**Comment by lasiecz** [comment]
Since this is my first post would you mind telling me how can i report it to Dev?

**Comment by Gbergz** [comment]
Oh sorry, here: https://github.com/McJtyMods/RFToolsBuilder/issues

**Comment by Gbergz** [comment]
Closing.
