### ISSUE TITLE
Industrial Forgoing Rancher not milking cows

### ISSUE THREAD

**Issue by cxcevents** [The-Nexus-Project/Limitless#41]
Rancher appears to work properly with Sheep but with cows you hear the milking action but no milk is produced. have tried all the other fluid machines in the mod and nothing works.

>  test #1: Same forge version, and same version of IF, and ONLY IF installed. Same behaviour, milking action, but no milk produced.
Other test #2: Latest 1.14.4 forge version, same version of IF. Still not working.
Other test #3: Latest forge, earlier versions (both of them I could install in my test pack through the twitch launcher). Still no go.

>

**Comment by Gbergz** [comment]
Probably a Mod Issue, report it to them on their issue tracker if it still happens.
