### ISSUE TITLE
Lighting in a chunk going dark despite being lit

### ISSUE THREAD

**Issue by cxcevents** [The-Nexus-Project/Limitless#42]
problem has been seen by multiple users.

breaking torches in the area and replacing them temporarily fixes the lighting but it seems to go back. 

i removed everything i had in that area and the glitch stopped. the next day the chunk next to it started doing the same thing. first time I had a dropper in the chunk being used to drop items, 2nd time in the adjacent chunk i had a dispenser setup. 

both vanilla versions

![unknown](https://user-images.githubusercontent.com/14831458/72762082-4ff39a80-3bac-11ea-9e00-0d1bb5ac73f5.png)

**Comment by ergoplato** [comment]
It could be related to this issue on Botania’s tracker: https://github.com/Vazkii/Botania/issues/3140

**Comment by Gbergz** [comment]
Should be fixed within Botania now.
