### ISSUE TITLE
Embellishcraft steel problem

### ISSUE THREAD

**Issue by syrun97** [The-Nexus-Project/Limitless#43]
**Describe what happened:**
I cant make steel from blast furnace(recipe conflict with Silent's item refined iron) and I cant use embellishcraft steel to make alloy machine frame

**To Reproduce**
Steps to reproduce (double check if you can do it yourself):
1. smelt iron in blast furnace
2. refined iron: lol no steel 4 u
3. smelted block and that gave steel.
4. Oredict: no 4 u

**Expected behavior**

iron in blast furnace -> steel
Alloy machine frame should use forge:ingots/steel in recipe too.

**Screenshots**
Use upload site like Imgur.
(Remove this text & the text above^ and only provide the link.)

**My OS (Mac/Win10/Linux)**
- win10

**Additional context**
Use Craft Tweaker

**Comment by Gbergz** [comment]
Fixed in next release.
EDIT: Added a recipe to create EmbellishCraft Steel Ingots from Refined Iron, just smelt it again. 👍 
Also gone ahead and added a 2nd recipe, identical to the existing one for Machine frame, just with "forge:ingots/steel" tag.
