### ISSUE TITLE
Server "Script" is Named After a Built-in, also not Linux

### ISSUE THREAD

**Issue by da3dsoul** [The-Nexus-Project/Limitless#44]
I'm just going to say, this isn't really necessary. It's just such a minor simple mistake that it's funny.

start cannot be used for script names, because if you type start, it will be extremely unintuitive, even if it works. Name it something like RunServer.bat

Anyone running a linux server (hosting aside) should be knowledgeable enough to open the bat and see how to convert it, but including a RunServer.sh would be helpful to newbs and people who can't be arsed.

Above all, your "working" server script relies on system Java without performing a version check. You should always perform a version check.

I haven't written it yet, but I'll do you guys a solid and write a more thorough script for not Mac (I don't negotiate with terrorists).

**Comment by bstock84** [comment]
I tend to agree that although a minor thing, most server packs include both .bat files as well as .sh files. In this case I simply made the .bat executable and it runs just fine with ./start.bat

I too would prefer something like ServerStart.bat/ServerStart.sh, sounds a bit more proper. But again these are minor differences.
