### ISSUE TITLE
Recipe conflict with Terracotta Bricks

### ISSUE THREAD

**Issue by craft90** [The-Nexus-Project/Limitless#48]
Both Mystical World and Embellishcraft adds terracotta bricks which leads to a recipe conflict where you always end up with MysticalWorld terracotta bricks.

**To Reproduce**
Steps to reproduce (double check if you can do it yourself):
1. Grab 4 terracotta
2. Place them in a 2x2 pattern in a workbench (I used the Simple Storage one)
3. You'll end up with MysticalWorld terracotta bricks

The recipes appear to be the same and so they overlap. Which is unfortunate as the Embellishcraft terracotta bricks are a lot fancier and adds in stairs, walls etc.

**Java Info:**
 - Java Version: version 8, build 1.8.0_241-b07
 - 64bit 

**My OS (Mac/Win10/Linux)**
- Windows 10 64bit

I used the native Minecraft launcher not the JAR launcher.

**Comment by Gbergz** [comment]
I'll fix this in v1.12 
Thanks for the report!

**Comment by craft90** [comment]
You're welcome.
