### ISSUE TITLE
Null pointer while using Paxel

### ISSUE THREAD

**Issue by Tommycat6278** [The-Nexus-Project/Limitless#5]

**Comment by Tommycat6278** [comment]
I made a iron paxel to save on hot bar slots but when I attempt to left click on any ore the game instantly crashes giving me a null pointer exception. I was trying to mine Inferium Ore.

**Comment by Gbergz** [comment]
Got a crash report to go with this?
What mod is the paxel from?

Edit: upload crash reports to sites like ([Paste.ee](https://paste.ee), [pastebin](https://pastebin.com) & [hastebin](https://hastebin.com).)

**Comment by Gbergz** [comment]
Did some digging and found out it's from the 'MoreProgression' mod. I'll disable the Paxels from that mod next update which in turn will "fix" the crash. I'll also try to report it to the mod dev of that mod.
Don't worry Paxels will still be available. The mod PickleTweaks has them & i didn't notice there were two sets of Paxels, which is now fixed.


Thank you for reporting this!
Feel free to re-open this issue if further issues arise from this mod.
