### ISSUE TITLE
1.13 update security issue

### ISSUE THREAD

**Issue by VoxelVixen** [The-Nexus-Project/Limitless#50]
My issue is that updating the pack via the startserver options seems to rely on downloading some jar file  from a site called https://yoosk.pl which i never heard of.

I only use/trust zip files from curseforge so unless you upload a normal server zip with config/mods/scripts/etc folders, i cant/wont update my server.

**Comment by Gbergz** [comment]
Latest update (when server files are approved.) Includes previous way of doing server files.
