### ISSUE TITLE
Please remove Journeymap from your packs.

### ISSUE THREAD

**Issue by mysticdrew** [The-Nexus-Project/Limitless#51]
You are in violation of our license agreement. 
https://journeymap.info/Modpack_FAQ

To continue use of Journeymap in your packs, you must remove it from your github repos and use the curse cdn for each install. Rehosting is strictly prohibited in our Terms of Use. 

Here are the instructions to get the file from the curse cdn without rehosting. 
Use this URL to get the metadata json 
`https://addons-ecs.forgesvc.net/api/v2/addon/${modId)/file/${fileId}`
 journeymap's modId : 32274, 
Journeymap 5.7.0 for MC 1.15.2 FileID 2894436 This can be found on curse for your specific required version. 
So the url is 
`https://addons-ecs.forgesvc.net/api/v2/addon/32274/file/2894436`
This will provide a json payload, in that payload you will find the downloadUrl in the respective field. 
For 1.15.2 the link is below
`https://edge.forgecdn.net/files/2894/436/journeymap-1.15.2-5.7.0beta1.jar`

**Comment by mysticdrew** [comment]
Your packs are already on curse, why do you rehost all the mods here?

**Comment by Gbergz** [comment]
Hey thanks for noticing that, didn't really think that one through to be honest. I've removed the mods from Github. All of them.

**Comment by mysticdrew** [comment]
> Hey thanks for noticing that, didn't really think that one through to be honest. I've removed the mods from Github. All of them.

Thanks you!
