### ISSUE TITLE
Server Crash 1.14 Server Files

### ISSUE THREAD

**Issue by MokahTGS** [The-Nexus-Project/Limitless#52]
**Describe what happened:**
Launching a server with the server files produces a server crash.

**Crash-reports**
https://pastebin.com/rGuk5bxA

**Java Info:**
 - Java Version: 
 - 64bit/32bit: Java 8 64b

**My OS (Mac/Win10/Linux)**
- win10

**Comment by Gbergz** [comment]
Limitless doesn't contain the Mod [MrCrayfish's Vehicle Mod](https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-vehicle-mod)
Please don't report issues with mods that aren't even in the pack.

**Comment by MokahTGS** [comment]
Yeah, just saw this...I'm a dummy

**Comment by Gbergz** [comment]
No problem :D 
But to solve this though you'll need to add this mod: [Obfuscate](https://www.curseforge.com/minecraft/mc-mods/obfuscate)

**Comment by MokahTGS** [comment]
Yes, I figured...my client installed it automatically and I forgot to grab it for our server.
