### ISSUE TITLE
Journeymap Crash?

### ISSUE THREAD

**Issue by MokahTGS** [The-Nexus-Project/Limitless#53]
**Describe what happened:**
Server Crashed...reason unknown.  Server was up and running with a couple people on and then it crashed.

**Crash-reports**
https://pastebin.com/mmBPPQF5

**Java Info:**
 - Java Version: 8 64b
 - 64bit/32bit: 

**My OS (Mac/Win10/Linux)**
- win10

**Comment by ImAK9** [comment]
@MokahTGS What you do is report it to the mod author and not on here.

**Comment by MokahTGS** [comment]
I will report it to journymap but here is also appropriate since the crash happened using this mod pack.

**Comment by MokahTGS** [comment]
Well they seem pretty rude, so I'm not sure they will get this fixed.  We just turned off Journeymap and are using another map mod.

**Comment by Gbergz** [comment]
Pretty sure it can be removed from server and still be used. Though some
features will be disabled. Sorry you’re having issues.

**Comment by Gbergz** [comment]
Closing this as it's a mod issue.
