### ISSUE TITLE
Biome ID conflict

### ISSUE THREAD

**Issue by craft90** [The-Nexus-Project/Limitless#54]
**Describe what happened:**
I launched my older save of the modpack. heading outside for a walk I noticed these Rifter mobs running at me, pursued by Sulks. As I headed deeper into that biome I quickly noticed that the ground was pink and these Sulks were everywhere. I soon realized that for some reason Druidcraft's Dark Wood Forest biome is in conflict with Midnight's Hill Fungi biome. There was over 200 of those Sulks around. The trees were the same but grass and mob spawning wasn't. The Rifters were burning too as they are undead aswell as not supposed to be out in the day  or in the Overworld.

**To Reproduce**
Steps to reproduce (double check if you can do it yourself):
Just take a look around. I don't know if this issue persist in new world or if it's a pre-generated world issue. (I'm however running the latest version of the Modpack, updated via Curse)

**Expected behavior**
Well I didn't expect a Midnight biome in the Overworld... or hundreds of Midnight mobs running about. 

**Java Info:**
 - Java Version: version 8 build 241
 - 64bit/32bit: 64bit

**My OS (Mac/Win10/Linux)**
- Win10

**Additional context**
Minecraft-version: 1.14.4
Modpack-version: 1.15
Forge: 28.2.3

**Comment by craft90** [comment]
The issue appear only in older saves it seems. I made a new test world and went flying about. In that save the Dark Forest biomeID was correct.
That said, it seems like the Sulks has a very high spawn rate when in the Overworld. I ran a kill entity command and it killed over 1650 sulks. The excessive spawn of these Sulks is kicking my CPU into overdrive and it's a i7 processor.

**Comment by Gbergz** [comment]
Closing this for now, feel free to re-open!
