### ISSUE TITLE
Server side freeze

### ISSUE THREAD

**Issue by sal-versij** [The-Nexus-Project/Limitless#55]
**Describe what happened:**
`The server doesn't respond`: the client can continue to play but blocks don't drop and chest don't open, also the world stop loading new chunks, I'm playing in singleplayer but TheOneProbe says server doesn't respond whenever I point a block.

**To Reproduce**
I don't know it happens randomly, I think is something with the loading of the world because change every time I change the view distance or I move

**Logs / Debuglogs**
It's not a crash and the log doesn't say anything just stop logging

**Java Info:**
 - Java Version: 1.8.0_221
 - 64bit/32bit: 64bit

**My OS (Mac/Win10/Linux)**
- Win10

**Additional context**
I update the modpack from 1.14 to 1.15, before there wasn't any problem, after the update it started, and not in the new chunks loaded but in the region I set my home so already loaded.

I'm not english so maybe my english is full of errors, sorry.

**Comment by Gbergz** [comment]
How much RAM do you currently have allocated to the server?
Also, you said you updated the modpack from 1.14 to 1.15? As in you downloaded [Limitless 2](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-2) or made your own 1.15 version of [Limitless 1](https://www.curseforge.com/minecraft/modpacks/tnp-limitless)?

**Comment by kkjdroid** [comment]
> Also, you said you updated the modpack from 1.14 to 1.15? As in you downloaded [Limitless 2](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-2) or made your own 1.15 version of [Limitless 1](https://www.curseforge.com/minecraft/modpacks/tnp-limitless)?

I think the OP means that they updated TNP 1 from its own version 1.14 to 1.15, still on Minecraft 1.14.4. 

I'm having the same issue very frequently, with standard "The server can't keep up" logs, on TNP 1.16 with Windows 10 and Java 1.8.0-241 x64. It happens every time I move more than ~200m from my base.

If I exit the world, the game freezes on the "Saving world" screen and the last log entry is `Mapping halted in <instance folder>\journeymap\data\mp\offline\DIM0`. If I forcibly close the game and reopen it, I'm back to an earlier state, often several minutes before the server stopped responding.

Also getting a NPE from JourneyMap, not sure if it's relevant: `Unexpected exception opening UI class journeymap.client.ui.fullscreen.Fullscreen: java.lang.NullPointerException`

**Comment by sal-versij** [comment]
> How much RAM do you currently have allocated to the server?
> Also, you said you updated the modpack from 1.14 to 1.15? As in you downloaded [Limitless 2](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-2) or made your own 1.15 version of [Limitless 1](https://www.curseforge.com/minecraft/modpacks/tnp-limitless)?

For the ram 8GB and yes I update the version of the pack from the twitch launcher that displayed the version 1.15 still in minecraft 1.14.4
