### ISSUE TITLE
Crash to desktop bugged items

### ISSUE THREAD

**Issue by sldains** [The-Nexus-Project/Limitless#56]
While hovering the mouse over certain items (a wrench, an enchanted sword, etc.) the game will suddenly hard crash to desktop. The items causing this seem so random and I'm not sure how to fix it. I'm playing on lan and some times it affects both of us and sometimes only one.

**Comment by Gbergz** [comment]
A crash report and pack version would be nice.

**Comment by Gbergz** [comment]
But I can’t promise It’ll get fixed since 1.14 is left in the dark now that 1.15 & 1.16 is out.

**Comment by sldains** [comment]
Sorry, this was with Limitless 2, not 1. Sent here by mistake. I resent the issue to 2.
