### ISSUE TITLE
Can't Download Modpack In Curseforge Due To Missing Dependency Error

### ISSUE THREAD

**Issue by RConTRS** [The-Nexus-Project/Limitless#58]
I Get An Error Everytime While Downloading TNP Limitless, Happens With Limitless 2 As Well

![Capture](https://user-images.githubusercontent.com/97401001/211308220-a7148067-bfdc-48f9-9122-1c8c7964170a.JPG)

**Comment by Gbergz** [comment]
Switch launcher. recommend ATLauncher. 

https://atlauncher.com/downloads

**Comment by RConTRS** [comment]
ATLauncher doesn't work with cracked accounts so i have to find an alternative myself, thanks anyways
