### ISSUE TITLE
Solar Flux Reborn causing crash on multiplayer server startup

### ISSUE THREAD

**Issue by NC256** [The-Nexus-Project/Limitless#6]
Just grabbed the latest v1.07 server files and upon loading the server it crashes. I've tried to launch it three times and get the exact same error each time.

I've changed a few things in the server.properties file like render distance, spawn protection, max players, etc. Nothing that I think would have caused this. Haven't added or removed any mods. Not really sure what would have caused this. Suggestions for a fix are welcomed and I would be glad to collect any more data that you think might be helpful.

Here's a pastebin of the crash: https://pastebin.com/Pek0F7E8
Also here's a pastebin of the last few lines of the server log before it tanked, which seems to have slightly more information in it: https://pastebin.com/k62CGYUP

**Comment by Gbergz** [comment]
Hey, i see that you’re using Java 9 which is not a recommended nor good version for Minecraft. Use Latest Java 8 64bit and try again! 

EDIT: And if that doesn't do anything. Go into the Twitch Launcher & unlock the pack so you can update mods. Then update Solar Flux Reborn to the latest version. Only that. Don't update any other mods as it might create issues. 

Now try again.

**Comment by NC256** [comment]
Spectacular! Rolled back to Java 8_191 and no more crashing. Server starts fine. Thanks for catching that!

**Comment by patitow** [comment]
I have rolled back to jre1.8.0_301 and my server still crashes, any clue? (current version of mod pack)
