### ISSUE TITLE
World Crashes upon start.

### ISSUE THREAD

**Issue by Speedy48702** [The-Nexus-Project/Limitless#7]
So I have really been enjoying this modpack, and I disconnect from my world to make sure it saves because it has been crashing a little but after I saved and tried to load back in it just crashed and has been doing that every time I try to load back into it. If anyone can help me try to get my world back I have been working a lot on it and would hate to restart everything.
 
Here is the crash report I get every time I try to load my world.
 
https://pastebin.com/tA4VxS6V

**Comment by Gbergz** [comment]
Do you by any chance have anything from Refined Storage in your world?

**Comment by Speedy48702** [comment]
> Do you by any chance have anything from Refined Storage in your world?

Yes, I do. I never had a problem with it since it was already in the modpack when I started.

**Comment by Gbergz** [comment]
I reported it on the Refined Storage github issue page:
https://github.com/raoulvdberge/refinedstorage/issues/2375

**Comment by Gbergz** [comment]
Closing this for now, this happens in other modpacks too it seems. So this will probably be fixed when the next Refined Storage update is live. And when that comes i'll post a hotfix update!

Re-open if any further issues comes!
