### ISSUE TITLE
MultiMC Unable to Launch

### ISSUE THREAD

**Issue by JacobHS** [The-Nexus-Project/Limitless#8]
**Describe the bug**
Tried running the pack on MultiMC and it would not even load. Crash report is down below. Any idea on how to fix it?

**Crash reports**
MultiMC version: 0.6.7-1375

Minecraft folder is:
C:/Users/Jacob/Desktop/MISC/MultiMC/instances/Limitless-1.07a/minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 1.8.0_231, using 64-bit architecture.

Instance update failed because: Component metadata update task failed while downloading from remote server:

Job 'Download of meta file net.minecraftforge/28.1.107.json' failed to process:
https://meta.multimc.org/v1/net.minecraftforge/28.1.107.json

**Comment by Gbergz** [comment]
Hey, simple & short answer. 
MultiMC doesn't support Forge 1.14, use twitch launcher.
Sorry for the inconvenience.

**Comment by JacobHS** [comment]
Ok thanks!
