### ISSUE TITLE
Pack will not load.

### ISSUE THREAD

**Issue by mikeskey** [The-Nexus-Project/Limitless#9]
After using the so called "fix" with the forge issue the pack still will not load. There should be no need for any sort of fix therefore something is wrong with the pack on your end not on the users. Please fix this problem promptly.

When trying to load the pack there is a new forge folder added even after following the steps and installing forge manually.

**Comment by Gbergz** [comment]
It seems issues like this one is random to be honest, works sometimes and sometimes not. I guess we have Forge to blame for these ones. They keep changing stuff behind the scenes and mods have to adapt to those changes. Sometimes mods do not adapt and then they don't update the mods to those changes and they break, not all the times but sometimes. 

Server files have been tested before release, they work. I've tested on multiple PCs including 2 server hosts. No issues. 

I'm sorry you're having this issue!

EDIT: I would suggest just keep trying, re-download the server files & try again.
In future updates i'm going to try and get a stable build out. As of now Limitless is kind of unstable. 
Stay tuned.

**Comment by cooljackgi** [comment]
i where able to start a server but not to start my game client :/ 
log says about:
Failed to find Minecraft resource version 1.14.4-20190829.143755

**Comment by Gbergz** [comment]
> i where able to start a server but not to start my game client :/
> log says about:
> Failed to find Minecraft resource version 1.14.4-20190829.143755

Hey, follow these steps and see if you can get the client to boot! Link:
https://github.com/The-Nexus-Project/Limitless/issues/1

**Comment by Gbergz** [comment]
Closing this for now, re-open if needed.
